### ISSUE TITLE
Invalid signature file digest for Manifest main attributes

### ISSUE THREAD

**Issue by SeaYang** [512433465/JacocoPlus#5]
作者你好，引用你的jar包，运行之后报如下异常：
Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at sun.security.util.SignatureFileVerifier.processImpl(Unknown Source)
	at sun.security.util.SignatureFileVerifier.process(Unknown Source)
	at java.util.jar.JarVerifier.processEntry(Unknown Source)
	at java.util.jar.JarVerifier.update(Unknown Source)
	at java.util.jar.JarFile.initializeVerifier(Unknown Source)
	at java.util.jar.JarFile.getInputStream(Unknown Source)
	at sun.misc.URLClassPath$JarLoader$2.getInputStream(Unknown Source)
	at sun.misc.Resource.cachedInputStream(Unknown Source)
	at sun.misc.Resource.getByteBuffer(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at com.yangtu.CoverageDemo.main(CoverageDemo.java:14)
这个是因为什么引起的呢？

**Comment by SeaYang** [comment]
已经解决了，解决方案：
使用压缩软件打开jar包 删除：META-INF目录下的除了mainfest.mf，.rsa及maven文件夹 以外的其他所有文件
